/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 low_poly_checkers.glb -t 
Author: barcin (https://sketchfab.com/barcin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-checkers-d7da09568b014912b683efc800091dfb
Title: Low poly checkers
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function LowPolyCheckers(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/low_poly_checkers.glb') as GLTFResult
  return (
    <group {...props} dispose={null}> //0.038
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} position={[-0.001, 0.019, -0.016]} scale={[0.15, 0.025, 0.15]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.black} position={[0.13, 0.054, 0.116]} rotation={[-Math.PI, 1.383, -Math.PI]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.white} position={[-0.096, 0.054, 0.116]} rotation={[-Math.PI, -0.909, -Math.PI]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.white} position={[-0.133, 0.054, 0.116]} rotation={[0, 1.276, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.white} position={[-0.096, 0.054, 0.078]} rotation={[-Math.PI, -0.506, -Math.PI]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.white} position={[-0.058, 0.054, 0.04]} rotation={[0, Math.PI / 2, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.white} position={[-0.096, 0.054, 0.041]} rotation={[-Math.PI, 0.763, -Math.PI]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.white} position={[-0.133, 0.054, 0.041]} rotation={[0, 0.588, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.white} position={[-0.058, 0.054, 0.003]} rotation={[-Math.PI, 0.764, -Math.PI]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.white} position={[-0.133, 0.054, 0.003]} rotation={[0, -0.151, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.white} position={[-0.096, 0.054, -0.035]} rotation={[0, 0.005, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.white} position={[-0.133, 0.054, -0.035]} rotation={[-Math.PI, 1.172, -Math.PI]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.white} position={[-0.096, 0.054, -0.073]} rotation={[0, Math.PI / 2, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.white} position={[-0.133, 0.054, -0.073]} rotation={[0, Math.PI / 2, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.white} position={[-0.096, 0.054, -0.111]} rotation={[0, Math.PI / 2, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.white} position={[-0.133, 0.054, -0.111]} rotation={[-Math.PI, 0.687, -Math.PI]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.white} position={[-0.096, 0.054, -0.148]} rotation={[-Math.PI, 1.387, -Math.PI]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.white} position={[-0.133, 0.054, -0.148]} rotation={[0, Math.PI / 2, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.black} position={[0.093, 0.054, 0.116]} rotation={[0, Math.PI / 2, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.black} position={[0.13, 0.054, 0.078]} rotation={[0, -0.998, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.black} position={[0.093, 0.054, 0.078]} rotation={[0, 1.299, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.black} position={[0.13, 0.054, 0.041]} rotation={[0, -1.146, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.black} position={[0.093, 0.054, 0.041]} rotation={[0, Math.PI / 2, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.black} position={[0.13, 0.054, 0.003]} rotation={[0, Math.PI / 2, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.black} position={[0.093, 0.054, 0.003]} rotation={[0, 1.054, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.black} position={[0.13, 0.054, -0.035]} rotation={[0, 0.926, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.black} position={[0.093, 0.054, -0.035]} rotation={[0, 0.324, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.black} position={[0.13, 0.054, -0.073]} rotation={[0, -1.116, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.black} position={[0.093, 0.054, -0.073]} rotation={[0, -1.213, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.black} position={[0.13, 0.054, -0.111]} rotation={[0, 0.079, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.black} position={[0.093, 0.054, -0.111]} rotation={[0, 0.519, 0]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.black} position={[0.13, 0.054, -0.148]} rotation={[-Math.PI, 0.061, -Math.PI]} scale={[0.015, 0.007, 0.015]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.black} position={[0.093, 0.054, -0.148]} rotation={[0, -0.837, 0]} scale={[0.015, 0.007, 0.015]} />
    </group>
  )
}

useGLTF.preload('/models/low_poly_checkers.glb')
